# Generated by Django 4.2 on 2023-06-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
